// This file is automatically generated from your CSS. Any edits will be overwritten.
export const canvasSettings: string;
export const fieldset: string;
export const label: string;
export const fieldsetInputs: string;
export const fieldsetFirstInput: string;
export const input: string;
export const colorInput: string;
